version: '3'
services:
  ### Mysql container
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest
      MYSQL_ROOT_HOST: '%' # needs to be enclosed with quotes

  app:
    build: .
    command: npm run start:dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
