FROM node:alpine

WORKDIR /usr/app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

#SERVER CONFIG
ENV SERVER_PORT=3000

#DATABASE CONFIG
ENV TYPEORM_CONNECTION=mysql
ENV TYPEORM_HOST=mysql
ENV TYPEORM_PORT=3306
ENV TYPEORM_USERNAMME=nest
ENV TYPEORM_PASSWORD=nest
ENV TYPEORM_DATABASE=nest
ENV DOCKER=true

#MAIL CONFIG
ENV MAIL_HOST=smtp.example.com
ENV MAIL_PORT=25
ENV MAIL_USER=user@example.com
ENV MAIL_PASSWORD=topsecret
ENV MAIL_FROM=noreply@example.com
ENV MAIL_SECURE=false

#AUTH CONFIG
ENV JWT_SECRET_KEY=MY_SECRET
ENV JWT_TIME_EXPIRATION=1h

#OTHERS CONFIG
ENV RECOVER_PASSWORD_URL=google.com

WORKDIR /usr/app/dist

CMD ["npm","run", "start:prod"]